[project]
name = "model-sales-val"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [

]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
# Add isort to ruff linting
extend-select = ["I"]

[tool.uv.workspace]
members = ["src"]
